 - hosts: nfs
   tasks:
     - name: Install the latest version of nfs-utils
       dnf:
         name: nfs-utils    
         state: latest
       become: yes

     - name: Install the latest version of net-tools
       dnf:
         name: net-tools    
         state: latest
       become: yes

     - name: Enable and start nfs-server
       systemd:
         name: nfs-server
         enabled: yes
         state: started
       become: yes
       
     - name: Copy exports file.
       template:
         src: ./exports.j2
         dest: /etc/exports
         owner: root
         group: root
         mode: 0644
       register: exports
       become: yes
       
     - name: Reload exportfs if /etc/exports changed
       command: /usr/sbin/exportfs -ra
       when: exports.changed
       become: yes

     - name: firewall configuration
       firewalld:
         service: "{{ item }}"
         permanent: yes
         state: enabled
         immediate: yes
       become: true
       with_items:
         - "nfs"
         - "rpc-bind"
         - "mountd"
       
     - name: reload service firewalld
       systemd:
         name: firewalld
         state: reloaded
       become: yes
