- hosts: master:workers
  tasks:
    - name: Copy hosts file.
      template:
        src: ./dns_hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
      become: yes
      
    - name: Add the br_netfilter module
      modprobe:
      name: br_netfilter
      become: yes
