- hosts: master:workers
  tasks:
    - name: Copy hosts file.
      template:
        src: ./dns_hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
      become: yes
      
    - name: Add the br_netfilter module
      modprobe:
        name: br_netfilter
      become: yes      
      
    - name: Add masquerade to firewall
      firewalld:
        masquerade: yes
        state: enabled
        permanent: true
      become: yes
      
      # Esta tarea se ejecuta aquí para abrir los puertos necesarios para instalar Calico en Azure
    - name: firewall configuration
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      with_items:
        - "8285/udp"
        - "8472/udp"

    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes

    - name: Copy k8f file
      template:
        src: ./k8f.j2
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: 0644
      become: yes
      
    - name: Applying k8s.conf
      command: /usr/sbin/sysctl --system
      become: yes      
      
    - name: Deactivate swapp
      command: /usr/sbin/swapoff  -a
      become: yes
      
    - name: Delete swap line from /etc/fstab
      shell: sed -i '/swap/d' /etc/fstab
      become: yes
      
    - name: Get docker repo
      shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      become: yes      

    - name: Install docker
      shell: dnf install docker-ce-19.03.14-3.el8 containerd.io -y
      become: yes
      
    - name: Enable and start docker
      systemd:
        name: docker
        enabled: yes
        state: started
      become: yes
      
    - name: Configure kubernetes repo
      template:
        src: ./kubernetes_repo.j2
        dest: /etc/yum.repos.d/kubernetes.repo
        owner: root
        group: root
        mode: 0644
      become: yes
      
    - name: Install kubelet,kubeadm and kubectl
      dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        disable_excludes: kubernetes
      become: yes
      
    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
      become: yes
