- hosts: master:workers
  tasks:
    - name: Copy hosts file.
      template:
        src: ./dns_hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
      become: yes
      
    - name: Add the br_netfilter module
      modprobe:
        name: br_netfilter
      become: yes      
      
    - name: Add masquerade to firewall
      firewalld:
        masquerade: yes
        state: enabled
        permanent: true
      become: yes

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes

    - name: Copy hosts file.
      template:
        src: ./k8f.j2
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: 0644
      become: yes
      
    - name: Applying k8s.conf
      command: /usr/sbin/sysctl --system
      become: yes      
      
    - name: Deactivate swapp
      command: /usr/sbin/swapoff  -a
      become: yes
      
    - name: Delete swap line from /etc/fstab
      shell: sed -i '/swap/d' /etc/fstab
      become: yes
      
    - name: Get docker repo
      shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      become: yes      

    - name: Install docker
      shell: dnf install docker-ce-19.03.14-3.el8 containerd.io -y
      become: yes
