- hosts: master
  tasks:
    - name: firewall configuration
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      with_items:
         - "6443/tcp"
         - "2379-2380/tcp"
         - "10250/tcp"
         - "10251/tcp"
         - "10252/tcp"
         - "10255/tcp"
       
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes
       
    - name: Configure Kudeadm
      shell: kubeadm config images pull
      become: yes
      
    - name: Enable access from workers
      firewalld:
        rich_rule: rule family=ipv4 source address=192.168.1.111/32 accept
        permanent: yes
        immediate: yes
        state: enabled
      become: yes
        
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes
        
    - name: Enable access to localhost work containers
      firewalld:
        rich_rule: rule family=ipv4 source address=172.17.0.0/16 accept
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
      become: yes
        
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes
        
    - name: Install CNI (Container Network Interface) plugin
      shell: kubeadm init --pod-network-cidr 192.169.0.0/16
      become: yes
    
      
