- hosts: workers
  tasks:
    - name: firewall configuration
      firewalld:
        port: "{{ item }}"
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      with_items:
         - "{10250,30000-32767}/tcp"
       
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes
       
    - name: Join the cluster
      shell: 
      become: yes
      
