- hosts: workers
  tasks:
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes
      
    - name: firewall configuration
      firewalld:
        port: "{{ item }}"
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      with_items:
         - "10250/tcp"
         - "30000-32767/tcp"
       
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: yes
       
    - name: Join the cluster
      shell: kubeadm join 10.0.1.10:6443 --toke q1aci3.vsocxuq2ng9atw4k --discovery-token-ca-cert-hash sha256:b27de9ae8740a52307a7a0ef7d52c66fff88c57289f9f53abc427781aa376afe
      become: yes
      
